Feat/native stl io
unibas-gravis/scalismo pull request #419
Opened 2024-01-12 00:08 UTC by madsendennis

Native scala implementation to read/write the STL format.
The implementation is ~6 times faster to write a PLY file and ~2.5 times faster to read. 

This is the first part of removing the VTK dependency in Scalismo, https://github.com/unibas-gravis/scalismo/issues/415

2024-01-19 12:32 UTC, Andreas-Forster approved these changes
I like the changes, they look reasonable small. To my suggestions, check what else need to be changed, especially if you accept the proposed renaming. This is not properly propagated.

As there is a test in place, I did not check every detail of the format how it is written.

2024-01-20 21:30 UTC, madsendennis commented on src/main/scala/scalismo/io/stl/STLMeshWriter.scala
> +  private val ORDER = ByteOrder.LITTLE_ENDIAN
From wikipedia: "numbers and are assumed to be little-endian, although this is not stated in documentation". I can add this comment in the file as well.

2024-01-20 21:32 UTC, madsendennis commented on src/main/scala/scalismo/io/stl/STLMeshReaderAscii.scala
> +      !data(2).startsWith("vertex") ||
I'll move this to a separate checkTriangleFormat function

2024-01-20 21:34 UTC, madsendennis commented on src/main/scala/scalismo/io/stl/STLMeshWriter.scala
> +      .order(ORDER).put(data.getBytes("UTF-8")).array())
Good spot. I see that both stl and ply in fact support ASCII, so should be updated accordingly.

2024-01-21 09:20 UTC, Andreas-Forster requested changes

2024-01-21 09:20 UTC, Andreas-Forster commented on src/main/scala/scalismo/io/stl/STLMeshReaderAscii.scala
> +      Point3D(parts(1).toFloat, parts(1).toFloat, parts(2).toFloat)
The indices seem to be a bug here. (1 1 2)

I will propose a PR soon also fixing this bug.

2024-01-21 09:53 UTC, Andreas-Forster commented on src/main/scala/scalismo/io/stl/STLHelpers.scala
> +package object STLHelpers {
Why is this a package object? Is there a reason for it?

2024-01-21 20:52 UTC, Andreas-Forster approved these changes

2024-01-22 10:39 UTC, merged